import * as React from 'react';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { App, Image } from '@/components';
import { TITLE } from '@/utils';

import './globals.css';

/* Core CSS required for Ionic components to work properly */
import '@ionic/core/css/core.css';

/* Basic CSS for apps built with Ionic */
import '@ionic/core/css/normalize.css';
import '@ionic/core/css/structure.css';
import '@ionic/core/css/typography.css';

import 'overlayscrollbars/overlayscrollbars.css';
import 'react-loading-skeleton/dist/skeleton.css';

const poppins = Poppins({
  weight: ['400', '600', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--ion-font-family',
});

export const metadata: Metadata = {
  title: 'Create Next App + Ionic SSR',
  description: 'Generated by create next app',
};

const tabLabels = ['Home', 'Account', 'Search', 'Settings'];

export default async function RootLayout({
  tabs,
  children,
}: {
  tabs: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={poppins.variable}>
      <body
        className={'fixed inset-0 z-0 min-h-screen bg-cover'}
        style={{ backgroundImage: "url('/background.png')" }}
      >
        <span className={'fixed inset-0 bg-slate-900 opacity-50'} />
        <App
          NavLogoComponent={
            <Image
              alt={'Acme Logo'}
              src={'/logo-no-background.png'}
              width={48}
            />
          }
          headerTitle={TITLE}
          options={{
            theme: 'ios',
            dark: true,
            // dark: false,
          }}
          tabbarProps={{
            icons: true,
            labels: true,
          }}
          tabLabels={tabLabels}
        >
          {tabs}
          {children}
        </App>
      </body>
    </html>
  );
}
